### ISSUE TITLE
Enable HTTPs for community.wheelmap.org

### ISSUE THREAD

**Issue by Xylakant** [sozialhelden/wheelmap#133]
We're loading some stylesheet resources from the blog, so we need to at least optionally offer TLS on the blog.

**Comment by thermann78** [comment]
Can be done as soon as certificate is there.

**Comment by holgerd** [comment]
@thermann78 status?

**Comment by thermann78** [comment]
Little bit weird. We have following situation:

1. Flexible HTTPS via Cloudflare. We cannot change to full HTTPS, because this is only contained in business account - pricing around 200$/mo.
2. Community.wheelmap.org is hosted on a virtual server without dedicated IP.

Both causes warnings on some browsers. What would be the best solution for this case, @Xylakant?

**Comment by holgerd** [comment]
@skade , can you help here?

2016-02-29 14:07 GMT+01:00 Timo <notifications@github.com>:

**Comment by holgerd** [comment]
Felix ist im Urlaub, aber Florian ist verfügbar.
ciao,h

2016-02-29 14:07 GMT+01:00 Timo <notifications@github.com>:

**Comment by skade** [comment]
Is it possible to move the resources over into the wheelmap or are those dynamically generated by the community page?

**Comment by thermann78** [comment]
It is WordPress. The files are physically located on our vServer, the sites are dynamically generated from MySQL.
We just moved them away from Spiderman in order of the separation of Ruby and PHP.

**Comment by holgerd** [comment]
@thermann78 can this be closed?

**Comment by holgerd** [comment]
we moved to news.wheelmap and this is SSL, so I close this.
