### ISSUE TITLE
Widget - language issue

### ISSUE THREAD

**Issue by cdupoiron** [sozialhelden/wheelmap#141]
Hey,

First, thanks for your work :)

I integrated some widget in our blog and i have langugae issue, it seems to be in russian or another language. How can i change it or fix it?

http://handinantes.fr/theatre-graslin/ => on the right side

![sc langugage issue](https://cloud.githubusercontent.com/assets/4683624/13058157/a3112b0c-d421-11e5-9b5e-01b0122113c0.png)

**Comment by holgerd** [comment]
Hi, great you are using the widget! 

I guess this is not a bug, but an unexpected feature. Try this:

1. On the machine you took this screenshot, go to http://wheelmap.org/map
1. Change the language in the upper right corner to french (or whatever you like)
1. Go back to http://handinantes.fr/theatre-graslin/ . It should be the same language.

Let me know if that works for you.

**Comment by cdupoiron** [comment]
Ooohhhh, thank you very much :)

**Comment by lennerd** [comment]
Hey @cdupoiron,

nice to see the widget in action. To fix this issue permanently you can try to add the language to the URL in your embed code:

Instead of using 'http://wheelmap.org/embed/your-key' you can use 'http://wheelmap.org/fr/embed/your-key'.

That should pin the language to france (or what ever language you choose).

But we should definitly optimize this in the widget builder in the profile section. So thanks for the feedback! :+1:

**Comment by lennerd** [comment]
To give you a more useful example:
```
<iframe width="300" height="400" src="//wheelmap.org/fr/embed/xQsTKqay6iPDyxhJYoTq#/?categories=government.education.shopping.food.leisure.health.misc.sport.tourism.accommodation.public_transfer&lat=47.2136504&lon=-1.5622236&zoom=18"></iframe>
```

Watch out for the `fr` in the URL, which points the content of the iframe to the french version of the wheelmap.

**Comment by cdupoiron** [comment]
It works like a charm ! :) thx @lennerd
