### ISSUE TITLE
500 error when adding email in /profile

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#318]
- I'm logged in as OSM-user garfield771 on wheelmap.org and go to http://wheelmap.org/profile/edit . I add a valid email address garfield@mailinator.com in the email input field and click save
- I expect to see a confirmation that my changes were saed.
- Instead, I see a server 500 error and the URL in the address bar is http://wheelmap.org/profile

In /admin I see the last user who successfully added an email address to his profile was June 21st (the day we deployed the rails update live).

**Comment by holgerd** [comment]
maybe related: #317

**Comment by schultyy** [comment]
Thuy and I tested on Staging and found out the following:
It seems to be the case that we run into some sort of timeout here because the unicorn worker gets killed after 30 secs and is restarted afterwards. The 502 occurs because the connection from Ngnix to Unicorn gets closed. The log has this error `upstream prematurely closed connection while reading response header from upstream`

**Comment by 1000miles** [comment]
This issue is fixed in the PR #332.
