### ISSUE TITLE
/node_types - Numbers cut off in view

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#329]
When browsing to http://wheelmap.org/node_types using Firefox (Mac), I cannot read the "Amount" column in the table:

 <img width="1438" alt="bildschirmfoto 2016-07-14 um 15 54 23" src="https://cloud.githubusercontent.com/assets/218506/16866497/876de626-4a6c-11e6-94ab-32a0242c3fcc.png">

**Comment by 1000miles** [comment]
We did a bit of research and found out following:

The node_types page is cut off in Firefox because the column for icons is using the `img alt text` instead of the icons. In Chrome the icons are broken but they are displayed on the column. 

Please see the difference:

![00000123](https://cloud.githubusercontent.com/assets/4077916/16950626/8e27e98c-4dc1-11e6-9c5e-607bfaa18cdf.png)

![00000124](https://cloud.githubusercontent.com/assets/4077916/16950635/97208120-4dc1-11e6-82ca-67622ee94fa6.png)


We had a look on the server and saw that the app tries to render icons that might not be there. To understand if the sprite (icons.zip) contains all icons, we need to have a complete list of icons that are supposed to be used/shown in this project.

@lennerd Because you might have a better overview of the icons list, can you please check if the current rendered sprite is complete and up-to-date? Merci.

**Comment by lennerd** [comment]
This does not use the icon sprite but the the `image_tag` helper. This returns the wrong path.

https://github.com/sozialhelden/wheelmap/blob/02412ab4465790ed6ab1c63171561e0013c6aab9/app/views/node_types/_node_type.html.haml#L7

For example: `/icons/dentist.png` instead of `/assets/icons/dentist.png`

**Comment by lennerd** [comment]
I also would suggest to just remove the old icons with the color background which are not used anywhere anymore.

**Comment by 1000miles** [comment]
@holgerd Can this be closed now? :)

![00000148](https://cloud.githubusercontent.com/assets/4077916/18304868/21a90cf0-74e5-11e6-97c4-131fec87761f.png)

**Comment by holgerd** [comment]
lgtm
