### ISSUE TITLE
If a translation is missing it should default to the English translation

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#344]
If a translation is missing it should default to the default translation which should be either German or English

This came up in 
https://github.com/sozialhelden/wheelmap/pull/343#issuecomment-234968989

**Comment by holgerd** [comment]
Reasoning: We must easily be able to find out what translations are missing. In Transifex missing strings are RED. If these are populated with english strings, this won't show up anymore. This risks that translations will be missing forever.

**Comment by holgerd** [comment]
@Svenyo recommended this as well and mentioned that it is unclear if the default should be German or English. Please involve her as well in this issue.

**Comment by lennerd** [comment]
I think English should be in every case the default language, as this is the most spoken language.

**Comment by lennerd** [comment]
I think this issue is based on a misunderstanding. @schultyy thought that our `js` based translation files we generate via `i18n:js:export` are coming directly from Transifex. Therefore he thought, that we fill in Englisch translations in Transifex when the current language translations are missing.

But the process is different. So again, yes, we us Transifex for translations.

These translations are synced via the command line tool `tx` with our `yaml` files you can find [here](https://github.com/sozialhelden/wheelmap/tree/master/config/locales). When Transifex has no translations strings, these files just do not contain them. So no english strings (except for the english source files of course) in here.

From this YAML files we then generate assets for the frontend which you can find [here](https://github.com/sozialhelden/wheelmap/tree/master/app/assets/javascripts/i18n). In these files missing translations are filled with the English source strings. This way we do not need to send the client two translations files including a fancy library concatenating both files to generate the correct translations.

We also need to distinguish between translations needed in Rails and translations needed in Ember or React. Rails is using the YAML files and fills missing translations automatically by using the source and translation strings. Ember and React are using both the generated i18n frontend assets.

I hope this clears things. 😉

**Comment by lennerd** [comment]
I need to reopen this as I just realized, that missing translations in Rails (so coming from the YAML files) are actually filled with German.

This is not easy to fix, as the current default locale is also used for routing.

 https://github.com/sozialhelden/wheelmap/blob/02412ab4465790ed6ab1c63171561e0013c6aab9/lib/rack_i18n_locale_switcher.rb#L18-L25
https://github.com/sozialhelden/wheelmap/blob/9949ee417f8d8ddd45a7d01043784683e52650d9/app/controllers/application_controller.rb#L32-L35

**Comment by lennerd** [comment]
A good example from the new node photo upload alerts:

![screenshot 2016-08-01 11 46 35](https://cloud.githubusercontent.com/assets/1609692/17290218/ad45ebcc-57dd-11e6-8ec1-ce696c5b56cd.png)

There are no translations yet. So in this example visiting the Spanish page shows the German translation.

**Comment by lennerd** [comment]
After a bit of testing I realized, that the URL part for the locale is not carried to next pages. So a locale is only added after the dropdown in the top right corner is used. Browsing to a new page will remove the locale but the language stays the same.

Maybe we then can use English as the default locale? Will make a PR for this. cc @holgerd

**Comment by holgerd** [comment]
Maybe we should not do this at all since it will change the content  of most of our URLs.

Today I see live:

- https://wheelmap.org/en/nodes/1296421604 --> 200 OK
- https://wheelmap.org/de/nodes/1296421604 --> 302 REDIRECT to https://wheelmap.org/nodes/1296421604

What we could do:

## Option 1: do not change, keep German
(Maybe just 302 to 301 because it is a permanent redirect.)

## Option 2: always redirect to language-specific URL

- https://wheelmap.org/nodes/1296421604 --> 301 REDIRECT to https://wheelmap.org/en/nodes/1296421604
-  https://wheelmap.org/de/nodes/1296421604 --> 200 OK

## Option 3: Have English as the non-locale URL

- https://wheelmap.org/en/nodes/1296421604 --> 301 REDIRECT to https://wheelmap.org/nodes/1296421604
- https://wheelmap.org/de/nodes/1296421604 --> 200 OK

**Comment by holgerd** [comment]
The goal of this issue was to prevent German text from showing up on non-German pages. Now we are discussing URLs etc.

Maybe we can solve this issue simply by making sure we have all translation strings in Transifex and then have everything translated.

**Comment by Svenyo** [comment]
Hi Holger, to have all strings translated for 22 languages will hardly ever be the case. If we make this a condition the we would constantly block ourselves from launching new features.

**Comment by 1000miles** [comment]
@holgerd 

cc @Svenyo 

Thanks for your inputs. Is there a final decision here? If not and you need technical support from us, please let us know. We can not progress here until a decision is made. Merci. :)

**Comment by holgerd** [comment]
@1000miles @lennerd @Hoverbear
I took half an hour together with @Svenyo to understand this issue better.

Our understanding is now:

- the main problem is that German text shows up on non-German pages, see https://github.com/sozialhelden/wheelmap/issues/344#issuecomment-236537027
- The solution suggested by @lennerd was to have English text on non-German and non-English pages by default, leading to bigger issues like #350 .
- We think this is not fixing the root cause of this issue
- Instead, Transifex (eg. @Svenyo and I) has to know when new untranslated strings are generated so we can decide to either have them translated or not (and accept that it will be German in certain languages)

So my suggestion is:

- open a new issue: "Make sure Transifex receives an info when new strings are generated"
- close #350 as wontfix.
- close this issue #344 as well as wontfix

**Comment by holgerd** [comment]
As dicussed yesterday we will close this as wontfix as well as the PR #350 .

But we are opening #435 to have a better translation process in the future.

**Comment by holgerd** [comment]
Explanation: wheelmap.org was already indexed with german content by search engine machines, if now the default language changes to english, this could have impact on SEO. Also, it is not fixing the root cause (mixed language content sites). That's why we'll focus on a better translation process instead.
