### ISSUE TITLE
In OSM deleted entries still shown on Wheelmap

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#368]
@1000miles:

Diese 3 grün markierten Orte sind Dubletten von grauen Orten und werden in der OSM bereits als gelöscht angezeigt, in der Wheelmap existieren sie weiter.

http://wheelmap.org/nodes/-430417027
http://wheelmap.org/nodes/-430407303
http://wheelmap.org/nodes/-430406408

Es scheint daher weiterhin ein Sync-Problem zu geben, obwohl die Datenbank im Backend die aktuellen POIs (- 2 Stunden) anzeigt.

**Comment by holgerd** [comment]
for reference:

http://www.openstreetmap.org/way/430417027/history
http://www.openstreetmap.org/way/430407303/history
http://www.openstreetmap.org/way/430406408/history

**Comment by 1000miles** [comment]
@holgerd 
cc @schultyy 

**Estimation to fix:**
- approx. 0.5 - 1 day

**Explanation:**
In case it's 'just' deleting the mention nodes, then it wouldn't take long but to be sure there are not a lot of other duplicates/removed nodes, then we need to put some research and tests on the sync issue.

**Comment by Xylakant** [comment]
The sync is a delta update, so if we lost some delta at some point it will be hard to identify what we're missing. A full import of the POIs likely would fix the problem.

**Comment by 1000miles** [comment]
@holgerd 

We discussed this internally and came to the conclusion that a **full import** is not something we can do `on the go` because it takes approx. 2-3 days (at least according to the docs). Before being able to do this, we need a sophisticated plan which also considers a page that says "sorry, we are down for maintenance!"

**conclusion:**
For now we will only delete these nodes manually on wheelmap as requested:

- //wheelmap.org/nodes/-430417027
- //wheelmap.org/nodes/-430407303
- //wheelmap.org/nodes/-430406408

@Svenyo & @holgerd If there are more nodes that need to be deleted manually, please post them here latest by `tue, sept 13`.

**Comment by 1000miles** [comment]
@Svenyo & @holgerd 

Following pois have been removed from the database as of today:
- http://wheelmap.org/nodes/-430417027
- http://wheelmap.org/nodes/-430407303
- http://wheelmap.org/nodes/-430406408
