### ISSUE TITLE
Add user infos to bug reports (mailto:)

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#370]
As a community supporter I want to have additional user infos when receiving a bug report via email, so I can help the user much faster.
- user clicks "report bug" (does not exist yet)
- new email opens (mailto:) 
- starting text: 'please describe info here but only in German or English please'
- the mail is also pre-filled with additional info:
  - operating system
  - browser version
  - is user logged in?
    - user name
    - OSM connected?
      - OSM-URL of user page
  - current zoom level
  - current lat/long of map
  - language
  - filter status of map (status or categories or WC enabled/disabled)
- user adds his/her problem description to this email and clicks send.

**Comment by Hoverbear** [comment]
The user agent should be sufficient for `operating system, browser version` and is probably the only way to get it in-browser.

**Comment by Xylakant** [comment]
passing all this information to the mail client may be difficult. information can only be passed via query string and not all mail clients accept message bodies. It's not a properly specified thing but more of an ad-hoc semi standard. If we want more structured issues we should probably have our own "report issue" form on the page. This could in the background create an issue on our private github tracker or send an email if we prefer.

**Comment by holgerd** [comment]
@Hoverbear Agree. I think some of those things can be looked up on the client side and for others we need to look it up in the app (eg username, loggedin status..)

**Comment by 1000miles** [comment]
@holgerd 

cc @schultyy 

**Estimation to fix:**
- approx. 2,5 -3 days

**Explanation:**
- concept & discussions
- user form
- mailing alerts
- pre-filled fields
- validations
- test cases

**Comment by Hoverbear** [comment]
Probably related to #349

**Comment by schultyy** [comment]
@holgerd Does the wheelmap have the information `OSM-URL of user page`? I can't find anything right now.

**Comment by holgerd** [comment]
@schultyy If we have the OSM username the page of interest is www.openstreetmap.org/user/USERNAME/history eg. www.openstreetmap.org/user/holgerd/history

**Comment by holgerd** [comment]
Let me know if/when I can test this and what the URL will be.

**Comment by schultyy** [comment]
@holger: We also need a new translation for the "Report bug" menu entry: 
![screen shot 2016-10-04 at 11 56 53](https://cloud.githubusercontent.com/assets/235808/19070043/be160d82-8a29-11e6-9851-eaf36300000f.png)

Right now it always says "report bug" whatever language is selected.

**Comment by holgerd** [comment]
@1000miles : Regarding the design of https://staging.wheelmap.org/en/community_support/new :
can you change it to this http://wheelmap.org/en/nodes/new/name_category ?

**Comment by holgerd** [comment]
translations here:
https://docs.google.com/spreadsheets/d/1EcLsWR_nud3hee0t2zDCWxKbqyLHlFOCirM1_6ZsGiI/edit?usp=sharing

Only one string seems to be cpmpletely new: "Abschicken"

**Comment by 1000miles** [comment]
Today we agreed on that @schultyy and me will continue work on it asap to make Svenja happy. :)

cc @holgerd @Svenyo

**Comment by schultyy** [comment]
We will provide a basic version of the support form (with features which are done already) in production asap.
The following topics are not done yet and will be delivered in addition:

- current zoom level
- current lat/long of map
- filter status of map (status or categories or WC enabled/disabled)

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd & @karolinamakaruk 

Can you please review the current community support form on staging (https://staging.wheelmap.org/pl/community_support/new), upload and start the translation process for this recource file, if the wordings are ok from your side? 

File to be uploaded on transifex:
https://github.com/sozialhelden/wheelmap/blob/master/config/locales/en/relaunch.yml

**Important note:**
The form is not completely done yet, the steps mentioned by @schultyy [here](https://github.com/sozialhelden/wheelmap/issues/370#issuecomment-263216786) are still open.

**Comment by 1000miles** [comment]
As agreed today we want to provide a short text hint and link to the [FAQ](news.wheelmap.org/faq) on the page `/community_support/new`. @holgerd will provide the text in german and english.

**Comment by schultyy** [comment]
Closed this too fast, we're still waiting on FAQ and translations, therefore reopening.

**Comment by holgerd** [comment]
@1000miles FAQ intro text:

EN
Please check the [frequently asked questions](http://news.wheelmap.org/en/faq/) for help first. If the solution to your problem is not there, please answer the following questions so we can fix it.

DE
Manchmal läuft etwas nicht rund. Bitte schaue Dir unsere [häufigen Fragen und Antworten](http://news.wheelmap.org/faq/) an bevor du uns schreibst. Wenn deine Frage dort nicht beantwortet ist, beantworte bitte die folgenden drei Fragen, damit wir das Problem lösen können.

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd 

Deployed on staging today, ready to be reviewed. :)

**Comment by Svenyo** [comment]
@1000miles cc @holgerd I've just checked an send a test report. Did you receive it?

There will be a minor correction necessary in the German wording.
Otherwise, there's one thing in my opinion, that's not ideal: The "Submit"-Button is half covered on my screen by the footer, same case for the German and the English version of the form.
Can this be fixed?

![bildschirmfoto 2016-12-13 um 17 26 53](https://cloud.githubusercontent.com/assets/20318534/21148772/9339f364-c159-11e6-9bd4-a3aae62fabb8.png)

**Comment by holgerd** [comment]
@1000miles What @Svenyo said and LGTM and ready to go live then.

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd 

Thank you for your feedback. We will replace the translation text according to your [feedback](https://github.com/sozialhelden/wheelmap/issues/370#issuecomment-266786765) and optimize the submit button.

Also we would love to suggest following additional tasks (for which we need your feedback/approval):

1. switch email template from plain text to html (or is plain text so far okay for you?)
2. optimize layout of community support form https://staging.wheelmap.org/community_support/new for mobile (mobile version, not mobile app)
3. fix hover effect on firefox (https://github.com/sozialhelden/wheelmap/issues/92) since this also effects the `Problem melden` link in the navigation

---

What do you mean by this?
```
I've just checked an send a test report. Did you receive it?
```

At the moment we are not able to check if an email has arrived due to following reasons:
- we have switched back the receiver of the problem reports to `bugs [ät] wheelmap.org` for which we don't have access
- we don't send a copy of a problem request back to the user who sent it

If you wish the user to get a copy, please let us know and we are happy to build this feature. :)

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd @karolinamakaruk 

Following tasks have been done, deployed on staging and can now be reviewed:
- [x] replace german text according to your [feedback](https://github.com/sozialhelden/wheelmap/issues/370#issuecomment-266786765)
- [x] optimize layout of community support form for mobile

**Open questions (if you want us to work on these tasks):**
- switch email template from plain text to html
- fix hover effect on firefox (#92) since this also effects the Problem melden link in the navigation

**Comment by 1000miles** [comment]
@svenyo cc @holgerd 

This community support form has been deployed on production with release [20161219152440](https://github.com/sozialhelden/wheelmap/releases/tag/production-20161219152440) today (2016-12-19).

**Comment by 1000miles** [comment]
Holger Dieterich wrote:
> I’m ok with plain text. It is only for internal use anyways

Therefore we close this ticket.
