### ISSUE TITLE
McDonalds is in OSM but does not show up in Wheelmap

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#446]
A user reports to have edited a McDonalds in Vienna using Wheelmap and it vanished from Wheelmap.

I found it here:
http://www.openstreetmap.org/way/61909416/history

But I can not see it here:
https://wheelmap.org/map#/?lat=48.15292948980208&lon=16.30155175924301

Neither can I see it on the iOS app

**Comment by holgerd** [comment]
@lennerd Can this be related to the problem we had in #309 ?

**Comment by lennerd** [comment]
I think #309 is fixed and therefore every place should be visible on the map at least on the highest zoom. I'm also not able to access the node detail page on the wheelmap so I guess it does not exist in our database either.

404: https://wheelmap.org/nodes/-61909416

**Comment by Svenyo** [comment]
Recent case like the one mentioned above:

Another McDonalds in Lehrte: http://www.openstreetmap.org/way/196118021 not in Wheelmap https://wheelmap.org/map#/?lat=52.38763425011613&lon=9.972852199999988

It's a McDonalds boycott... ;-)

**Comment by Hoverbear** [comment]
Perhaps we should recommend users go fishing instead.

![catch-fish](https://cloud.githubusercontent.com/assets/130903/20972039/e51b3104-bc93-11e6-9f83-0620df4c9f0c.gif)

**Comment by Svenyo** [comment]
Another strange case:
https://www.openstreetmap.org/way/33615555
Two days ago, the Icon had been displayed correctly on Wheelmap.org, it has now disappeared again.

**Comment by holgerd** [comment]
maybe related: #521

**Comment by Svenyo** [comment]
Similarity of all those places not shown: They are "ways" on OSM. Maybe this could be an approach to examine the problem.

**Comment by Xylakant** [comment]
i don't think we actually import ways.

**Comment by schultyy** [comment]
So I digged a bit. My first clue was that since it's a way on OSM it's not imported at all. This is not true for the following reasons:

- Next to the McDonalds is a parking lot. It's a way as well and available on wheelmap
- The job logs tell that this has been on Wheelmap as well. The osm ID shows up in the logs together with the edited fields


My feeling is, that this has been deleted, two possible options here:

- Either this has been deleted via the MySQL console interface or Active Admin
- Or this has been deleted during osm sync

**Comment by schultyy** [comment]
I had a look at the MySQL log to see if there's anything useful. I see `INSERT` statements for our McDonalds but can't see any logged `DELETE` statement.

**Comment by schultyy** [comment]
I am closing this one with Won't fix because it's not possible to be certain how this McDonald's disappeared.
