### ISSUE TITLE
Bug:  New place without the address and geolocation

### ISSUE THREAD

**Issue by karolinamakaruk** [sozialhelden/wheelmap#483]
I tried to create a new place using  https://wheelmap.org/en/nodes/new/name_category. 
I didn't filled address and gelocation.
I couldn't create the point and also I didn't get any error message. It was only loading. No result.

**Comment by holgerd** [comment]
- I tested this (logged-in as OSM-user holgerd using the englisch locale of wheelmap.org) as well with location name "test" and category bank. My Chrome location was shared with Wheelmap. I keep clicking next in the flow and "save" on the last overview page.
- I expect to get an error message since no lat/lon was given or confirmed by me
- Instead, I see a spinner animation (gave up after 2min looking at it)

**Comment by schultyy** [comment]
@holgerd when should it complain about the missing lat/lon? On the last page? Or on this screen? 
<img width="927" alt="screen shot 2016-12-08 at 11 55 32" src="https://cloud.githubusercontent.com/assets/235808/21007466/43025884-bd3d-11e6-82af-7d2959540751.png">

**Comment by schultyy** [comment]
Just documenting my current findings on this one:

When I click through the form without filling out anything, the Developer console shows the API calls it performs. They all result in a 422 Unprocessably Entity. This means, validation already happens but results are not shown yet.

**Comment by holgerd** [comment]
LGTM. I see an error message now on staging when not  entering any address.
