### ISSUE TITLE
Fix photos uploaded by Wheelmap_Visitor

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#596]
Hi @1000miles,

just saw that probably thousands of pics (I assume all pics in the premium pois of Streetspotr) that had been collected and uploaded using the user Wheelmap_visitor from our last Streetspotr crowdsourcing campaigns are not shown in the detailed view.

I assume that we caused this new bug when we recently changed the permission for the Wheelmap_visitor into tagging the accessibility and toilet status only. #477  

Example:
POI "Monkeyman"
https://wheelmap.org/en/nodes/369681660
https://wheelmap.org/en/admin/pois/369681660/photos

![bildschirmfoto 2017-03-30 um 14 05 37](https://cloud.githubusercontent.com/assets/20318534/24503440/6487bcac-1552-11e7-89dc-b50c4c29ac9c.png)

![bildschirmfoto 2017-03-30 um 14 03 59](https://cloud.githubusercontent.com/assets/20318534/24503412/48c34be4-1552-11e7-9803-285a766cd01a.png)

![bildschirmfoto 2017-03-30 um 14 04 53](https://cloud.githubusercontent.com/assets/20318534/24503411/48c320a6-1552-11e7-84d3-fc325a759021.png)

**Comment by 1000miles** [comment]
We had a first look into the server logs and this is the **NGINX** output:

```
2017/03/30 14:28:57 [error] 14542#0: *6092606 rewrite or internal redirection cycle while internally redirecting to "/system/uploads/photo/000/067/190/gallery_preview.jpg.html.html.html.html.html.html.html.html.html.html.html", client: <OBFUSCATED>, server: asset0.wheelmap.org, request: "GET /system/uploads/photo/000/067/190/gallery_preview.jpg HTTP/1.1", host: "asset1.wheelmap.org", referrer: "https://wheelmap.org/en/nodes/369681660"
2017/03/30 14:28:57 [error] 14542#0: *6092607 rewrite or internal redirection cycle while internally redirecting to "/system/uploads/photo/000/067/189/gallery_preview.jpg.html.html.html.html.html.html.html.html.html.html.html", client: <OBFUSCATED>, server: asset0.wheelmap.org, request: "GET /system/uploads/photo/000/067/189/gallery_preview.jpg HTTP/1.1", host: "asset1.wheelmap.org", referrer: "https://wheelmap.org/en/nodes/369681660"
```

Similar issue (**internal redirection cycle**) occured recently as reported here:
https://github.com/sozialhelden/wheelmap/issues/480#issuecomment-279956306

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd @karolinamakaruk 

# Update, 2017, April 4:

## What we found out so far:

- the broken images only occur with the premium provider `streetspotr` but not with the other premium providers (e.g. Stiftung Gesundheit, Stiftung Leben pur, etc.)
- looking at the last updated dates of several pois the broken images might exist since a while - at least since 2013
- looking into the rails console we can see that when the attribute `image_processing` is flagged as `true` the images are broken while the images show up correctly when the attribute is set to `false` or `nil`

Example 1 (broken images):
```shell
irb(main):003:0> photo = Photo.find_by(id: 73276)
=> #<Photo id: 73276, caption: nil, image: "original.jpg", image_processing: true, poi_id: 1882401734, user_id: OBFUSCATED, taken_at: nil, created_at: "2015-12-17 18:30:25", image_width: nil, image_height: nil, image_gallery_ipad_retina_width: nil, image_gallery_ipad_retina_height: nil, image_thumb_width: nil, image_thumb_height: nil, image_thumb_iphone_width: nil, image_thumb_iphone_height: nil, image_thumb_iphone_retina_width: nil, image_thumb_iphone_retina_height: nil, image_gallery_iphone_width: nil, image_gallery_iphone_height: nil, image_gallery_iphone_retina_width: nil, image_gallery_iphone_retina_height: nil, image_gallery_ipad_width: nil, image_gallery_ipad_height: nil, image_gallery_width: nil, image_gallery_height: nil, image_tmp: nil, image_gallery_preview_width: nil, image_gallery_preview_height: nil>
```

Example 2 (working images):

```shell
irb(main):002:0> photo = Photo.find_by(id: 55630)
=> #<Photo id: 55630, caption: nil, image: "original.jpg", image_processing: nil, poi_id: 1882401734, user_id: OBFUSCATED, taken_at: nil, created_at: "2015-07-10 11:06:14", image_width: 3264, image_height: 2448, image_gallery_ipad_retina_width: 1536, image_gallery_ipad_retina_height: 2048, image_thumb_width: 100, image_thumb_height: 100, image_thumb_iphone_width: 56, image_thumb_iphone_height: 80, image_thumb_iphone_retina_width: 112, image_thumb_iphone_retina_height: 160, image_gallery_iphone_width: 320, image_gallery_iphone_height: 427, image_gallery_iphone_retina_width: 640, image_gallery_iphone_retina_height: 853, image_gallery_ipad_width: 768, image_gallery_ipad_height: 1024, image_gallery_width: 450, image_gallery_height: 600, image_tmp: nil, image_gallery_preview_width: 180, image_gallery_preview_height: 180>
```
- similar behavior in the database: when the `image_processing` is flagged as `NULL` then all other image meta tags are set as `NULL` as well

Example:
```shell
+-------+---------+--------------+------------------+------------+---------+----------+---------------------+-------------+--------------+---------------------------------+----------------------------------+-------------------+--------------------+--------------------------+---------------------------+---------------------------------+----------------------------------+----------------------------+-----------------------------+-----------------------------------+------------------------------------+--------------------------+---------------------------+---------------------+----------------------+-----------+-----------------------------+------------------------------+
| id    | caption | image        | image_processing | poi_id     | user_id | taken_at | created_at          | image_width | image_height | image_gallery_ipad_retina_width | image_gallery_ipad_retina_height | image_thumb_width | image_thumb_height | image_thumb_iphone_width | image_thumb_iphone_height | image_thumb_iphone_retina_width | image_thumb_iphone_retina_height | image_gallery_iphone_width | image_gallery_iphone_height | image_gallery_iphone_retina_width | image_gallery_iphone_retina_height | image_gallery_ipad_width | image_gallery_ipad_height | image_gallery_width | image_gallery_height | image_tmp | image_gallery_preview_width | image_gallery_preview_height |
+-------+---------+--------------+------------------+------------+---------+----------+---------------------+-------------+--------------+---------------------------------+----------------------------------+-------------------+--------------------+--------------------------+---------------------------+---------------------------------+----------------------------------+----------------------------+-----------------------------+-----------------------------------+------------------------------------+--------------------------+---------------------------+---------------------+----------------------+-----------+-----------------------------+------------------------------+
| 55630 | NULL    | original.jpg |             NULL | 1882401734 | OBFUSCATED | NULL     | 2015-07-10 11:06:14 |        3264 |         2448 |                            1536 |                             2048 |               100 |                100 |                       56 |                        80 |                             112 |                              160 |                        320 |                         427 |                               640 |                                853 |                      768 |                      1024 |                 450 |                  600 | NULL      |                         180 |                          180 |
| 73276 | NULL    | original.jpg |              1   | 1882401734 | OBFUSCATED | NULL     | 2015-12-17 18:30:25 |        NULL |         NULL |                            NULL |                             NULL |              NULL |               NULL |                     NULL |                      NULL |                            NULL |                             NULL |                       NULL |                        NULL |                              NULL |                               NULL |                     NULL |                      NULL |                NULL |                 NULL | NULL      |                        NULL |                         NULL |
```


### Examples:

Working images:
- https://wheelmap.org/en/nodes/1414413931 (version 4, updated January 21, 2014 23:30)
- https://wheelmap.org/en/nodes/315107960 (version 7, updated August 06, 2013 18:53)
- https://wheelmap.org/en/nodes/302040454 (version 8, updated	September 25, 2014 23:27)
- https://wheelmap.org/en/nodes/266328637 (version 9, updated February 29, 2016 13:29)
- https://wheelmap.org/en/nodes/689928445 (version 12, updated January 19, 2015 08:36)


Broken images:
- https://wheelmap.org/en/nodes/251908511 (version 4, updated May 13, 2016 19:13)
- https://wheelmap.org/en/nodes/292093177 (version 8, updated July 31, 2015 15:07)
- https://wheelmap.org/en/nodes/248071869 (version 4, updated August 06, 2013 18:07)
- https://wheelmap.org/en/nodes/2525070530 (version 4, updated November 28, 2016 16:54)
- https://wheelmap.org/en/nodes/-90843416 (version 1, updated October 26, 2014 18:12)

Partly broken images:
- https://wheelmap.org/en/nodes/1882401734 (version 7,  updated July 10, 2015 11:06)

## Conclusion:
- there is no specific pattern behind broken images due to `date ranges` or `versions` but behind the flag `image_processing` and 1 provider (streetspotr only)

## Questions:
- While csv files seem to get imported and exported from and for premium providers via rake tasks we are unsure about the process how the images uploads from providers get into wheelmap project? Does streetspotr use their own api and upload the images in their app and we finally need to import them manually here via a rake task? 

Unfortunately we could not find enough documentation until now.

**Comment by holgerd** [comment]
Is it possible that the images were added as "wheelchair_visitor"? And that we changed his permissions recently?

@Svenyo mentioned that this might be a trace.

**Comment by Svenyo** [comment]
@1000miles: Yes, we always get a csv-file back from them where all URLs are listed and we imported them manually in the past.

**Comment by 1000miles** [comment]
@Svenyo Can we have a phone call to talk about the usual csv import/export process with providers and document it?

**Comment by 1000miles** [comment]
### Update, 2017-04-07

- How many provided pois exist?

```shell
# => 18624
```

- How many provided pois are coming from streetspotr?
```shell
# => 15557
```
- How many photos that were created by streetspotr don't show up?

```shell
# => 14733 

created on 2014-01-07: 1x
created on 2015-12-17: 14732x
```

### Notes:

- according to our database statistics the image issue exist at least since **dec 2015**, probably a bit earlier
- the images that don't show up on the provided pois don't exist physically on the server even though the image-url has been generated, e.g. https://asset3.wheelmap.org/system/uploads/photo/000/073/802/original.jpg
- user authentication should not have an effect on the import

### Error output delayed_job.log:

```shell
2015-12-24T07:54:58+0100: [Worker(delayed_job host:OBFUSCATED pid:25847)] CarrierWave::Workers::ProcessAsset failed with Errno::ENOENT: No such file or directory @ rb_sysopen - /var/apps/wheelmap/production/releases/OBFUSCATED/public/system/uploads/photo/000/073/802/original.jpg - 19 failed attempts
2015-12-24T07:54:58+0100: [Worker(delayed_job host:OBFUSCATED pid:25847)] PERMANENTLY removing CarrierWave::Workers::ProcessAsset because of 20 consecutive failures.
```
- this open ticket might be related to our current issue: https://github.com/sozialhelden/wheelmap/issues/59#issuecomment-168674437 

---

@Svenyo cc @holgerd 

We suggest following:

- [ ] create simple csv file that map with the current streetspotr rake task to get it working
- [ ] improve csv format to match with streetspotr import rake task => @Svenyo Could you please provide us the csv file from ticket #59 for testing (we get a `404 error`)? https://www.dropbox.com/s/h6copt6wq8pji3c/2015-11-16-streetspotr-contributions-wheelmap-CSVs.zip?dl=0
- [ ] import streetspotr images into wheelmap db #59

**Comment by 1000miles** [comment]
ping @Svenyo 

Who can give us the latest csv version (2015-11-16) that came back from streetspotr? :)

**Comment by Svenyo** [comment]
Hi @1000miles, please find attached the last CSV files that we received from Streetspotr.

[stufenspotsexporte.zip](https://github.com/sozialhelden/wheelmap/files/913430/stufenspotsexporte.zip)

**Comment by 1000miles** [comment]
@svenja cc @holger 

When trying to import the `stufenspotsexporte.zip` from november 2015 we encounter following:

```shell
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x8A' for column 'caption' at row 1: INSERT INTO `photos` (`caption`, `created_at`, `image`, `image_processing`, `poi_id`, `taken_at`, `user_id`) VALUES ('Der Beweis das ich auch vor der Nummer 2 stand..😊', '2017-04-13 08:25:57', 'original.jpg', 1, 314137172, '2015-10-31 23:08:39', 2)

```
Looking at the csv we could find the line (`'Der Beweis das ich auch vor der Nummer 2 stand..😊'`) where the emoji is set. 

Running `SHOW table status LIKE 'photos'` in the database we see the encoding as `utf8_unicode_ci`.

In order to fix this we either 
- a) have to create a rake task that checks for future specific characters (e.g. emoji) and remove them in advance before we import
- b) allow the mysql db to handle emjois by changing the encoding from `utf8` to `utf8mb4`. 

`utf8mb` should be able to read all previous `utf8` entries but the `varchar(255)` will be reduced to `varchar(191)` since `utf8mb4` handles 4-byte-characters while `utf8` handles 3-byte-characters. 

Could you please let us know what you prefer?

**Comment by holgerd** [comment]
ping @Svenyo

**Comment by 1000miles** [comment]
@Svenyo && @holgerd 

We finally found a fix (solution a) => converter) for the emojis without the need to change the database encoding. :) 

**Another question:**
@Svenyo As we can see some duplicates in the csv file (which blows up the volume), can you please explain us what the differences are for example for:

`refId` vs. `attr.Id`
`title` vs. `attr.Name`
`longitude` vs. `attr.Lon`
`SpotCity` vs. `attr.City`

In order to prevent permanent modifications of the rake import task in the future, is it possible to agree on formats, columns, etc. with streetspotr?

**Comment by 1000miles** [comment]
#### Update, 2017-04-25:

So we could finally get the rake import task working and improved the branching concept and print out messages to have a better understanding what is currently happening during the import process.

**Example:**
```
Skipped: Removed POI (osm_id is blank and POI is nil).
Step: yes, Toilet: no, Indoor: no -> Status: no, Toilet: no.
Photo with osm_id 708431655 saved!
Photo without osm_id saved!
Couldn't find POI with 'osm_id'=463297399
Skipped: Invalid Photo Line (osm_id 463297399 is not blank but POI is nil)
Skipped: Removed POI (osm_id is blank and POI is nil).
Skipped: Removed POI (osm_id is blank and POI is nil).
Couldn't find POI with 'osm_id'=-147553604
```

**Example Screenshots after rake import:**

<img width="1252" alt="00000295" src="https://cloud.githubusercontent.com/assets/4077916/25379174/79802acc-29ac-11e7-831d-a01b0056bd0e.png">
<img width="1250" alt="00000296" src="https://cloud.githubusercontent.com/assets/4077916/25379191/83c57ac8-29ac-11e7-830d-57487ab6cdbf.png">


---

@TODO

- display URL for each photo of a provided_poi
- locate provided_pois with regions
- agree on pre-conditions for new imports in the future to avoid duplicates - tbd: @Svenyo

**Comment by Svenyo** [comment]
@1000miles cc @holgerd Thanks for solving this! I cannot explain you why the columns you mentioned as duplicate are necessary either... Do you still want me to clarify with streetspotr?

**Comment by 1000miles** [comment]
@Svenyo Yes, that would be great, then we could remove all the duplicate columns instead of appending more and more columns (which makes it hard to read because we have to scroll aside a lot). 

It would also help to agree on columns names, etc. I already started a wiki entry for this:
https://github.com/sozialhelden/wheelmap/wiki/Premium-Providers:-Import-and-Export-CSV-files

Please feel free to add/edit the infos after you have checked in with streetspotr. Thank you. :)

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd 

We are currently test running the import rake task on the staging server and face another value insert error message which is why it is necessary to agree on specific formats with streetspotr (e.g. caption should not be longer than 255 varchar)? 

```
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Data too long for column 'caption' at row 1: INSERT INTO `photos` (`caption`, `created_at`, `image`, `image_processing`, `poi_id`, `taken_at`, `user_id`) VALUES ('Hier sieht man nochmal diesen Weg vom vorigem Bild. Man sieht hier aber auch, das man sich einen Teil des alpinums auch von dem groem weg aus angucken kann. Auch diesen groen Weg knnte man als Eingang bezeichnen. Das alpinum ist Teil des Rhododendron-Parks . Es gibt eigentlich keinen klar definierten Eingangsbereich.', '2017-04-27 14:08:45', 'original.jpg', 1, 1406586867, '2015-09-03 09:29:01', 5)
```

**This is the caption string that is too long and therefore causes problems:**
```
Hier sieht man nochmal diesen Weg vom vorigem Bild. Man sieht hier aber auch, das man sich einen Teil des alpinums auch von dem groem weg aus angucken kann. Auch diesen groen Weg knnte man als Eingang bezeichnen. Das alpinum ist Teil des Rhododendron-Parks . Es gibt eigentlich keinen klar definierten Eingangsbereich.
```

According to this counter it is `318` characters long.
https://charcounter.com/en/

How do we handle such long data at the moment, just cut it?

**Comment by holgerd** [comment]
AFAIK we did not define the max. length of a description with streetspotr beforhand (cc @Svenyo ), so I suggest we truncate it for this import and ask the partner to enforce tha max 255 characters next time with its users.

**Comment by svenja** [comment]
Sorry, but why am I in this conversation? 

Kind Regards, Svenja 

Am 1. Mai 2017 10:35:31 MESZ schrieb Holger Dieterich <notifications@github.com>:
>AFAIK we did not define the max. length of a description with
>streetspotr beforhand (cc @Svenyo ), so I suggest we truncate it for
>this import and ask the partner to enforce tha max 255 characters next
>time with its users.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sozialhelden/wheelmap/issues/596#issuecomment-298305328

-- 
Sent from my Android phone.

**Comment by Svenyo** [comment]
@svenja Sorry, it seems there was a wrong mention. ;-)

**Comment by 1000miles** [comment]
**Update, 2017, June 8**

Research results so far:

- 14.733 photos between `2014-01-07 17:44:38` and `2015-12-17 18:35:22` in production 
  - have the attribute `image_processing=true` (1)
  - have null resized versions (e.g. image_width: null, image_height: null)
  - were uploaded by user_id: 1 (wheelmap_visitor)
- the non-resized images also effect pois, not only provided pois => we can exclude that it has something explicitely to do with the streetspotr rake task (but since streetspotr also uses the anonymous account `wheelmap_visitor` this could have been effected by this bug)
- in the past the accounts `wheelmap_visitor` and `wheelmap_android` were supposed to NOT be able to upload images but somehow it started the Carrierwave backgrounder delayed job, created a image paths and also the `original.jpg` which isn't there => we recently introduced the flag `anonymous` to all users (false by default). when we now upload images with these two accounts, it is not possible anymore.

Examples:
https://wheelmap.org/nodes/2739053220
https://wheelmap.org/nodes/355922690

```shell
| 73991 | original.jpg |                1 | 2739053220 |       1 | 2015-12-17 18:35:20 |        NULL |
| 73992 | original.jpg |                1 | 2739053220 |       1 | 2015-12-17 18:35:20 |        NULL |
| 73938 | original.jpg |                1 |  355922690 |       1 | 2015-12-17 18:35:13 |        NULL |         NULL |
```

URLs to original.jpg for poi 2739053220:
- https://asset2.wheelmap.org/system/uploads/photo/000/073/991/original.jpg => not found
- https://asset0.wheelmap.org/system/uploads/photo/000/073/992/original.jpg => not found
- https://asset1.wheelmap.org/system/uploads/photo/000/073/938/original.jpg => not found



### Some stats:

```shell
mysql> SELECT id, image, image_processing, poi_id, user_id, created_at, image_width FROM photos WHERE image_width IS NULL AND user_id = 1;

+-------+--------------+------------------+------------+---------+---------------------+-------------+--------------+
| id    | image        | image_processing | poi_id     | user_id | created_at          | image_width | image_height |
+-------+--------------+------------------+------------+---------+---------------------+-------------+--------------+
| 21627 | original.jpg |                1 |  314401618 |       1 | 2014-01-07 17:44:38 |        NULL |         NULL | 
| 73991 | original.jpg |                1 | 2739053220 |       1 | 2015-12-17 18:35:20 |        NULL |         NULL |
| 73992 | original.jpg |                1 | 2739053220 |       1 | 2015-12-17 18:35:20 |        NULL |         NULL |
| ..... | ............ |                . | .......... |       . | ................... |        .... |         .... | 
| 74005 | original.jpg |                1 | 1869122958 |       1 | 2015-12-17 18:35:22 |        NULL |         NULL |
+-------+--------------+------------------+------------+---------+---------------------+-------------+--------------+
14733 rows in set (0.03 sec)


```

### Conclusions:

- According to `Carrierwave backgrounder` docs `true` for image_processing means that the image resizing process is incomplete while `false` indicates it is complete. Since we are using that gem for delayed jobs to resize images this could have been the reason why the image processing did not pass through for those photos uploaded by `wheelmap_visitor`
- When we now upload images in production they appear immediately. Our hunch here is that the image resizing bug was fixed in the past but the 14733 broken images have not been corrected/removed so far. The 14733 effected images are useless since we do not have even the originals of them. Deleting them would be the most obvious next step?

**Comment by svenja** [comment]
Please take me out of the loop! Thank you!

sv

Am 08.06.17 um 09:22 schrieb Thuy Le:

**Comment by anngreenberg** [comment]
@svenja I'm sorry. You're listed as a participant and we can't undo that.  However, you can unsubscribe from the notifications in the sidebar.

**Comment by Svenyo** [comment]
@1000miles @anngreenberg @holgerd Reviewed as in https://github.com/sozialhelden/wheelmap/issues/167#issuecomment-311608771

**Comment by anngreenberg** [comment]
Import is done. Therefore closing.
