### ISSUE TITLE
Configure routes that match `/beta/*` to reach the Rails application

### ISSUE THREAD

**Issue by opyh** [sozialhelden/wheelmap#644]
Currently I can't access https://staging.wheelmap.org/beta/nodes/3230907861#/?lat=52.5417&lon=13.3884 – according to the Rails logs, this request does not reach the Rails application. It should be routed the same as https://staging.wheelmap.org/beta (which is reachable and gets a response from the Rails app server).

**Comment by 1000miles** [comment]
Probably related: https://github.com/sozialhelden/wheelmap/issues/411#issuecomment-249613722

**Comment by 1000miles** [comment]
@opyh So the `/beta` is white listed on staging now. :)

We were thinking about using the prefix for `/beta/*` via nginx but we noticed some slight changes  in the new front-end URLs along with the `node detail page view`.  In order to provide a proper solution we would love to ask if this is intended and if yes, would you mind to explain to us the new concept of it tomorrow?

![00000389](https://user-images.githubusercontent.com/4077916/29371326-644a3abc-82a8-11e7-8db0-2920127fdeba.png)

**Comment by 1000miles** [comment]
Deployed to [staging-20170817105118](https://github.com/sozialhelden/wheelmap/releases/tag/staging-20170817105118) and [production-20170817112353](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170817112353) today. Closed.

We also did a manual edit in `wheelmap_staging.conf` and `wheelmap_production.conf` on each server.
