### ISSUE TITLE
Login via OSM not possible - 500 error

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#675]
I'm logged our on https://wheelmap.org/en/users/sign_in and click on "Login with Openstreetmap". I expect to go to OSM to login. Instead, I go to https://wheelmap.org/en/users/auth/osm and see a 500 error something went wrong.

**Comment by 1000miles** [comment]
@holgerd cc @Svenyo @anngreenberg 

Thanks for reporting this ticket. Looks as if it's related to osm https change as well.

```
I, [2018-05-16T11:10:55.845438 #18637]  INFO -- : Started GET "/users/auth/osm" for 162.158.89.27 at 2018-05-16 11:10:55 +0200
F, [2018-05-16T11:10:55.893838 #18637] FATAL -- :
Net::HTTPRetriableError (301 "Moved Permanently"):
  lib/rack_i18n_locale_switcher.rb:29:in `call'
  librato-rack (0.6.0) lib/librato/rack.rb:94:in `process_request'
  librato-rack (0.6.0) lib/librato/rack.rb:64:in `call'
```

Affected links:
https://wheelmap.org/users/auth/osm

@holgerd
Since there are a lot of osm-related links still using `http` in the wheelmap project, do you want us to change them all for now and test each of them individually before we find more breaking changes?

**Comment by holgerd** [comment]
> Since there are a lot of osm-related links still using http in the wheelmap project, do you want us to change them all for now and test each of them individually before we find more breaking changes?

@1000miles yes please.

**Comment by 1000miles** [comment]
@holgerd cc @Svenyo @anngreenberg 

The reported error is fixed on production by PR # 284 (chef-repo). Please test the login/registration link on https://wheelmap.org/users/sign_in and confirm. Merci. :)

**Comment by opyh** [comment]
Works for me 👍🏻

**Comment by holgerd** [comment]
works for me, thanks!
