### ISSUE TITLE
Mention door width?

### ISSUE THREAD

**Issue by skade** [sozialhelden/wheelmap#85]
From user feedback: 

https://twitter.com/kkvie/status/677481495288782848

![mobile app](https://cloud.githubusercontent.com/assets/47542/11870861/a2b98bde-a4cb-11e5-96c7-d1336b33b975.jpg)

Does not mention door widths and they can get problematic at some places. Would that be a good addition to mention?

**Comment by holgerd** [comment]
Since this is just a representation of http://wiki.openstreetmap.org/wiki/DE:Key:wheelchair , changing the meaning of an existing OpenStreetMap-key should be discussed with the OSM community in the wiki or mailing list.

My hunch/hope is that most people will recognize extremely narrow doors and tag them acordingly.
